baseURL = "/"
languageCode = "en-us"
title = "Household Chores Tasklist"
theme = "kube"
description = "A household chore planner that's printable."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "clint@madebyclint.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
